package codenames

import (
	"math/rand"
	"net/http"
	"path/filepath"
	"strings"
)

const tpl = `
<!DOCTYPE html>
<html>
    <head>
        <title>Codenames - Play Online</title>
        <script src="/static/app.js?v=0.02" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" href="/static/game.css" />
        <link rel="stylesheet" type="text/css" href="/static/lobby.css" />
        <link rel="shortcut icon" type="image/png" id="favicon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAA8SURBVHgB7dHBDQAgCAPA1oVkBWdzPR84kW4AD0LCg36bXJqUcLL2eVY/EEwDFQBeEfPnqUpkLmigAvABK38Grs5TfaMAAAAASUVORK5CYII="/>

        <script type="text/javascript">
             {{if .SelectedGameID}}
             window.selectedGameID = "{{.SelectedGameID}}";
             {{end}}
             window.autogeneratedGameID = "{{.AutogeneratedGameID}}";
        </script>
    </head>
    <body>
		<div id="app">
		</div>
    </body>
</html>
`

type templateParameters struct {
	SelectedGameID      string
	AutogeneratedGameID string
}

func (s *Server) handleIndex(rw http.ResponseWriter, req *http.Request) {
	// Told a bare "no cache" once and still hit stale games behind a
	// Cloudflare Tunnel -- Cloudflare (and browsers) will still cache a
	// no-cache/must-revalidate response opportunistically. no-store is
	// the one directive that means "don't keep a copy of this at all",
	// which is what a page that must always reflect whichever container
	// is currently running actually needs.
	rw.Header().Set("Cache-Control", "no-store")

	dir, id := filepath.Split(req.URL.Path)
	if dir != "" && dir != "/" {
		http.NotFound(rw, req)
		return
	}

	autogeneratedID := s.getAutogeneratedID()

	err := s.tpl.Execute(rw, templateParameters{
		SelectedGameID:      id,
		AutogeneratedGameID: autogeneratedID,
	})
	if err != nil {
		http.Error(rw, "error rendering", http.StatusInternalServerError)
	}
}

func (s *Server) getAutogeneratedID() string {
	const attemptsPerWordCount = 5

	s.mu.Lock()
	defer s.mu.Unlock()

	if rand.Intn(5) == 1 {
		if vanityID, ok := s.maybeFindVanityGameIDLocked(); ok {
			return vanityID
		}
	}

	var words []string
	autogeneratedID := ""
	for i := 0; ; i++ {
		wordCount := 2 + i/attemptsPerWordCount

		words = words[:0]
		for j := 0; j < wordCount; j++ {
			w := s.gameIDWords[rand.Intn(len(s.gameIDWords))]
			words = append(words, w)
		}

		autogeneratedID = strings.Join(words, "-")
		if _, ok := s.games[autogeneratedID]; !ok {
			break
		}
	}
	return autogeneratedID
}

var preferredGameIDs = []string{
	"top-secret",
	"double-agent",
	"codebreaker",
	"mission-briefing",
	"spy-vs-spy",
	"cover-blown",
	"eyes-only",
	"need-to-know",
	"dead-drop",
}

func (s *Server) maybeFindVanityGameIDLocked() (string, bool) {
	perm := rand.Perm(len(preferredGameIDs))
	for _, i := range perm {
		id := preferredGameIDs[i]
		if _, ok := s.games[id]; !ok {
			return id, true
		}
	}
	return "", false
}
